version: '3.8'

services:
  tally:
    build: .
    image: morveus/tally:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/tally.db
    restart: unless-stopped